version: '3'
services:
  frontend-booking-apps:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: zodysatria/fe-booking-apps:latest
    ports:
      - '3000:80'
    depends_on:
      - backend-booking-apps
  backend-booking-apps:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: zodysatria/be-booking-apps:latest
    ports:
      - '8080:8080'
  consumer-booking-apps:
    build:
      context: ./consumer
      dockerfile: Dockerfile.consumer
    image: zodysatria/consumer-booking-apps:latest
    ports:
      - '8081:8081'
    depends_on:
      - backend-booking-apps
  zookeeper:
    image: 'bitnami/zookeeper:latest' 
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - frontend-booking-apps
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  booking-apps:
    external: true
