# image dasar
FROM golang:1.21.0-alpine3.18 as builder

# mengatur folder kerja
WORKDIR /app

# menyalin kode ke container
COPY . .

# compile aplikasi
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

# menggunakan Alpine Linux sebagai image dasar, untuk image yang dihasilkan
FROM alpine:latest

# menyalin aplikasi dari builder container
COPY --from=builder /app/app .

# ekspos port 
EXPOSE 8080

# menjalankan aplikasi
CMD ["./app"]